version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=true
      - SECRET_KEY=dev-secret-key-change-in-production
      - API_VERSION=v1
      - API_TITLE=Google Trends Quantile Forecaster API
      - API_DESCRIPTION=API for forecasting Google Trends data using LSTM models
      - RATE_LIMIT_DEFAULT=100/hour
      - MLFLOW_TRACKING_URI=sqlite:///mlflow.db
      - MLFLOW_EXPERIMENT_NAME=google_trends_forecaster
      - DATA_DIR=data
      - MODELS_DIR=models
      - LOGS_DIR=logs
      - PYTRENDS_DELAY=1
      - PYTRENDS_RETRIES=3
      - PYTRENDS_TIMEOUT=30
      - DEFAULT_BATCH_SIZE=5
      - DEFAULT_EPOCHS=150
      - DEFAULT_PREDICTION_WEEKS=25
      - DEFAULT_LSTM_UNITS=4
      - LOG_LEVEL=INFO
      - CORS_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
      - HOST=0.0.0.0
      - PORT=5000
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./logs:/app/logs
      - ./mlruns:/app/mlruns
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 